# Generated by Django 3.1 on 2020-08-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefonoContacto', models.IntegerField(verbose_name='Teléfono')),
                ('tipoDeSangre', models.CharField(choices=[('A+', 'A RH+'), ('A-', 'A RH-'), ('B+', 'B RH+'), ('B-', 'B RH-'), ('AB+', 'AB RH+'), ('AB-', 'AB RH-'), ('O+', 'O RH+'), ('O-', 'O RH-')], max_length=25, verbose_name='Tipo de Sangre')),
                ('poseeTransporte', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Posee transporte')),
                ('informacionAdicional', models.TextField(blank=True, null=True, verbose_name='Información adicional')),
                ('cantidadReportado', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'donante',
                'verbose_name_plural': 'donantes',
            },
        ),
    ]
